# DisasterResponsebAnalytics/docker-compose.yml

name: disaster-response-analytics

networks:
  disaster_response:
    driver: bridge   

services:
  postgres:
    image: postgres:16
    container_name: dr_postgres
    networks:
      - disaster_response 
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5434:5432"               # host:container
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db_init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 15s


  pgadmin:
    image: dpage/pgadmin4:9
    container_name: dr_pgadmin
    networks:
      - disaster_response
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "5050:80"
    volumes:
      - ./pgadmin/servers.json:/pgadmin4/servers.json:ro
    healthcheck:
      test: ["CMD-SHELL", "bash -c '</dev/tcp/127.0.0.1/80' >/dev/null 2>&1"]
      interval: 15s
      timeout: 5s
      retries: 12
      start_period: 20s


  etl:
    build:
      context: ./etl
      dockerfile: Dockerfile
    container_name: dr_etl
    networks:
      - disaster_response
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      FEMA_API_URL: ${FEMA_API_URL}
      TABLE_NAME: ${TABLE_NAME}
      TABLE_NAME_FLAT: ${TABLE_NAME_FLAT}
      LOAD_MODE: ${LOAD_MODE}
      BATCH_SIZE: ${BATCH_SIZE}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      POLL_ONCE: ${POLL_ONCE}
      POLL_INTERVAL_SEC: ${POLL_INTERVAL_SEC}

    command: ["python","-u","etl.py"]
    restart: unless-stopped

volumes:
  postgres_data:
